// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFbVKXMWJ7YFipTT0NhLmqB93PNZcgo6w',
    appId: '1:112227182320:web:799bc08ddb2026f1984435',
    messagingSenderId: '112227182320',
    projectId: 'flutter-boba-app-42eb3',
    authDomain: 'flutter-boba-app-42eb3.firebaseapp.com',
    storageBucket: 'flutter-boba-app-42eb3.appspot.com',
    measurementId: 'G-ZJ6BHQC0KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ri_dNZ9xMgfmx58YRYfWiRzgUOpAQyg',
    appId: '1:112227182320:android:ac63de9fca322e2a984435',
    messagingSenderId: '112227182320',
    projectId: 'flutter-boba-app-42eb3',
    storageBucket: 'flutter-boba-app-42eb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKMobBcoGQKAFcpVKvp0BPKRl6QzLIQu0',
    appId: '1:112227182320:ios:69713ce1342a2ee3984435',
    messagingSenderId: '112227182320',
    projectId: 'flutter-boba-app-42eb3',
    storageBucket: 'flutter-boba-app-42eb3.appspot.com',
    iosClientId: '112227182320-km1hve4poehbrk1gf7upviac1a19l054.apps.googleusercontent.com',
    iosBundleId: 'com.example.bobaTeaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKMobBcoGQKAFcpVKvp0BPKRl6QzLIQu0',
    appId: '1:112227182320:ios:559f26b09619a40d984435',
    messagingSenderId: '112227182320',
    projectId: 'flutter-boba-app-42eb3',
    storageBucket: 'flutter-boba-app-42eb3.appspot.com',
    iosClientId: '112227182320-cfd1ov3dnhmo3dvrsr43dtkaf3n89l90.apps.googleusercontent.com',
    iosBundleId: 'com.example.bobaTeaApp.RunnerTests',
  );
}
